image:
  file: .gitpod.Dockerfile

tasks:
  - init: make
    command: make test
    name: build

vscode:
  extensions:
    - ms-vscode.cmake-tools@1.6.0:lvoCR5usjseB5thI3sZhWA==
    - llvm-vs-code-extensions.vscode-clangd@0.1.8