language: c
dist: focal
addons:
 apt:
  packages:
   - cmake
   - cmake-data
   - gcc
   - g++
   - python3
   - lcov
   - socat
   - gengetopt
   - valgrind
   - libgtest-dev
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - make GCOV=1 gcov
after_success:
  - coveralls --lcov-file build/src/tests/coverage.info.cleaned --no-gcov
