language: c
addons:
 apt:
  sources:
   - george-edison55-precise-backports
   - ubuntu-toolchain-r-test
  packages:
   - cmake
   - cmake-data
   - gcc-5
   - g++-5
   - python-virtualenv
   - lcov
   - socat
   - gengetopt
   - valgrind
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - make GCOV=1 gcov
after_success:
  - coveralls --exclude-pattern 'lib/xml/*' --exclude-pattern 'gtest-src/*' --exclude-pattern 'src/tests/*' --exclude-pattern '/usr/*' --gcov-options '\-lp' --verbose
